M48
; DRILL file {KiCad (6.0.6)} date Wed Aug 24 09:29:42 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-24T09:29:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.5118
%
G90
G05
T1
X5.0079Y-3.8189
X6.4094Y-3.8189
T2
X5.374Y-3.8189
X6.0433Y-3.8189
T0
M30
