M48
; DRILL file {KiCad (6.0.6)} date Tue Aug 23 20:40:47 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-23T20:40:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
%
G90
G05
T1
X5.3622Y-3.8583
X6.7638Y-3.8583
T2
X5.6004Y-3.948
T0
M30
